# Generated by Django 3.2.6 on 2021-08-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='images')),
                ('type', models.CharField(choices=[('folder', 'folder'), ('image', 'image'), ('word', 'word'), ('widget', 'widget')], max_length=255)),
                ('isOpen', models.BooleanField(default=False)),
                ('isFocusedOnWindow', models.BooleanField(default=False)),
                ('isMinimized', models.BooleanField(default=False)),
                ('link', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innerFiles', to='frontend.file')),
            ],
        ),
    ]
