# Generated by Django 3.2.6 on 2021-08-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210814_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innerFiles', to='frontend.file'),
        ),
    ]
