# Generated by Django 3.2.6 on 2021-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210815_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
