# Generated by Django 3.2.6 on 2021-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('folder', 'folder'), ('image', 'image'), ('office', 'office'), ('widget', 'widget')], max_length=255),
        ),
    ]
