# Generated by Django 3.2.6 on 2021-08-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='title_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('folder', 'folder'), ('image', 'image'), ('office', 'office'), ('widget', 'widget'), ('browser', 'browser')], max_length=255),
        ),
    ]
