# Generated by Django 3.2.6 on 2021-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20210820_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='link_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='link_kk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='link_ru',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
