# Generated by Django 3.2.6 on 2021-08-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_article_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.ImageField(default=None, upload_to='articles/%Y/%m/%d/'),
        ),
    ]
