# Generated by Django 3.2.6 on 2021-08-28 08:40

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_file_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('icon', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные ссылки',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='region',
            field=models.CharField(choices=[('Региональные', 'Региональные'), ('Тараз', 'Тараз'), ('Байзакский район', 'Байзакский район'), ('Жамбылский район', 'Жамбылский район'), ('Жуалынский район', 'Жуалынский район'), ('Кордайский район', 'Кордайский район'), ('Меркенский район', 'Меркенский район'), ('Мойынкумский район', 'Мойынкумский район'), ('Район имени Т.Рыскулова', 'Район имени Т.Рыскулова'), ('Сарысуский район', 'Сарысуский район'), ('Таласский район', 'Таласский район'), ('Шуский район', 'Шуский район')], default='Региональные', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
    ]
